numero1 = int(input("Ingrese el primer numero: "))
numero2 = int(input("Ingrese el segundo numero: "))
numero3 = int(input("Ingrese el tercer numero: "))
print("El mayor numero es: ",max(numero1, numero2, numero3))
print("El menor numero es: ",min(numero1, numero2, numero3))